### DISCUSSION TITLE
Snap package discussion

### DISCUSSION THREAD

**Discussion by soumyaDghosh** [diegopvlk/Dosage#57] [General]
Thank you for the snap package. Feel free to mention me, with any issue with the snap. BTW, you can have workflows for the snap to test if it builds or not.

**Comment by soumyaDghosh** [comment]
BTW, just noticed, so, letting you know, plug `login-session-observe` doesn't auto connect. You'll need to make a request in the forum asking for it to auto connect.

**Comment by diegopvlk** [comment]
Thank you for the snapcraft.yaml :)

So is `login-session-observe` unnecessary? Does it do the same thing as dbus session?

Another thing I noticed is that the notification icons are not showing properly, do I need something extra to show symbolic icons? They're not showing on the top bar (app menu) either.

**Comment by soumyaDghosh** [comment]
> So is `login-session-observe` unnecessary? Does it do the same thing as dbus session?

https://github.com/diegopvlk/Dosage/blob/main/io.github.diegopvlk.Dosage.json#L12

As much I know from the docs, it's the snap equivalent to this of flatpak. So, you need to go and make a request in the forum for making this plug auto connect, else, this plug needs to be manually connected. It's the like the process of security checking, simply because this is a sensitive plug.



> Another thing I noticed is that the notification icons are not showing properly, do I need something extra to show symbolic icons? They're not showing on the top bar (app menu) either.

Can you show me the actual icons you want? I don't have a non ubuntu installation to test with.

BTW, notification doesn't seem to be working. No idea why, in my tests it did.

**Comment by diegopvlk** [comment]
I just need to check if the system is returned from suspension. From my tests it seems to be working, which I assume is because of the dbus in slots: https://github.com/diegopvlk/Dosage/blob/41c2efff6b3d4ca283128a00c75a8e1ff4352583/snap/snapcraft.yaml#L36-L39

This is where it's used:
https://github.com/diegopvlk/Dosage/blob/41c2efff6b3d4ca283128a00c75a8e1ff4352583/src/window.js#L126

Since it's working without `login-session-observe` being active I guess it can be safely removed.

> Can you show me the actual icons you want? I don't have a non ubuntu installation to test with. 

https://github.com/diegopvlk/Dosage/blob/main/data/icons/hicolor/symbolic/apps/io.github.diegopvlk.Dosage-symbolic.svg

It's just the symbolic icon for the app, it shows on the app menu and notifications, I didn't need to do anything special in the flatpak, it just works normally. In the snap it shows like this:

![image](https://github.com/diegopvlk/Dosage/assets/25941156/77a1f414-fa03-4607-9c7e-ae49db201241)

> BTW, notification doesn't seem to be working. No idea why, in my tests it did.

For me it's working fine, tested on my machine with fedora and in a vm with ubuntu 22.04, so not sure what's wrong.

**Comment by soumyaDghosh** [comment]
> I just need to check if the system is returned from suspension. From my tests it seems to be working, which I assume is because of the dbus in slots:

I think it's necessary. Though, I am not able to reproduce the user case. But, to talk with `org.freedesktop.login1.Manager`, you must need this plug.
https://github.com/snapcore/snapd/blob/master/interfaces/builtin/login_session_observe.go



> It's just the symbolic icon for the app, it shows on the app menu and notifications, I didn't need to do anything special in the flatpak, it just works normally. In the snap it shows like this:

Got it, snaps hardcode the desktop icon path, simply because Unity often faces issues with themed desktop icon. And as gnome has also ditched it with gnome 45, I think you should not think too much about it.



> For me it's working fine, tested on my machine with fedora and in a vm with ubuntu 22.04, so not sure what's wrong.

Well, it was my fault. I set the timings wrong to test with.

**Comment by diegopvlk** [comment]
> But, to talk with org.freedesktop.login1.Manager, you must need this plug.

Ok then

> Though, I am not able to reproduce the user case

Set a treatment for today and a time less than now.
Make sure there is no notifications showing and suspend your pc. 
After waking from suspension, see if there is a new notification, if yes, it means it's working.

> Got it, snaps hardcode the desktop icon path, simply because Unity often faces issues with themed desktop icon. And as gnome has also ditched it with gnome 45, I think you should not think too much about it.

I don't care about the app menu icon. But eventually I want to show the custom icon in the notification (haven't figure it out how yet). So I would prefer that at least this one works.

**Comment by soumyaDghosh** [comment]
> I don't care about the app menu icon. But eventually I want to show the custom icon in the notification (haven't figure it out how yet). So I would prefer that at least this one works.

Yeah obviously they will. This is done in the desktop file and nothing related to your app. Check in `/var/lib/snapd/desktop/applications/dosage-tracker_dosage_tracker.desktop`

EDIT: Confirmed, `login-session-observe` is needed.

**Comment by diegopvlk** [comment]
> Confirmed, login-session-observe is needed.

Then it's a mystery on how it's working for me
![image](https://github.com/diegopvlk/Dosage/assets/25941156/487db6b4-0715-4852-a4ac-09976633810e)

But I'll make the request anyway

**Comment by soumyaDghosh** [comment]
> Then it's a mystery on how it's working for me

Is this the vm of ubuntu or any other distro?

**Comment by diegopvlk** [comment]
> Is this the vm of ubuntu or any other distro?

This is a pc with fedora 39. I can't test in a vm, suspension doesn't work.

**Comment by soumyaDghosh** [comment]
> This is a pc with fedora 39. I can't test in a vm, suspension doesn't work.

Probably you haven't setup the confinement properly in fedora. Replacing the SeLinux, is tough in fedora. So, the confinement didn't work properly.

**Comment by diegopvlk** [comment]
@soumyaDghosh Hey, do you know what are the necessary changes to make for Libadwaita 1.6/GNOME 46?

**Comment by soumyaDghosh** [comment]
> @soumyaDghosh Hey, do you know what are the necessary changes to make for Libadwaita 1.6/GNOME 46?

Until libadwaita 1.6 is officially released it'll not be added into the gnome-sdk. When it's official, it'll added, if you want to use prerelease, you can build it from the source. Also, `core24` is coming soon. You should upgrade to that also when released.

**Comment by diegopvlk** [comment]
>  Also, core24 is coming soon

Got it

> Until libadwaita 1.6 is officially released

It was released today. So I don't have to do anything, just wait for `ubuntu/gnome-sdk/` to update?

**Comment by soumyaDghosh** [comment]
> It was released today. So I don't have to do anything, just wait for `ubuntu/gnome-sdk/` to update?

Exactly. It'll be updated and pushed to the users soon.

**Comment by diegopvlk** [comment]
@soumyaDghosh Thanks!

**Comment by soumyaDghosh** [comment]
> @soumyaDghosh Thanks!

BTW, I guess you mean libadwaita 1.5?

**Comment by diegopvlk** [comment]
> BTW, I guess you mean libadwaita 1.5?

Ops, yes 1.5

**Comment by soumyaDghosh** [comment]
@diegopvlk 

https://github.com/ubuntu/gnome-sdk/pull/198

Also I think better to move this issue to a discussion

**Comment by diegopvlk** [comment]
@soumyaDghosh Appreciate it!

**Comment by diegopvlk** [comment]
Hey @soumyaDghosh, I'm trying to build the snap with core24 and the new sdk.

This is the new snapcraft.yaml:

```yaml
name: dosage-tracker
base: core24
adopt-info: dosage-tracker
grade: stable
confinement: strict

parts:
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: "v0.12.0"
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ""

  dosage-tracker:
    after: [blueprint-compiler]
    plugin: meson
    source: https://github.com/diegopvlk/Dosage.git
    source-tag: "v1.6.1"
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH
      - GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0:/snap/gnome-46-2404-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}
    build-packages:
      - libvulkan-dev
      - libxkbcommon-dev
      - libportal-gtk4-dev
    meson-parameters:
      - --prefix=/snap/dosage-tracker/current/usr
    override-pull: |
      craftctl default
      sed -i -e 's|@GJS@|/snap/dosage-tracker/current/gnome-platform/usr/bin/gjs|g' src/io.github.diegopvlk.Dosage.in
    organize:
      snap/dosage-tracker/current: .
    parse-info: [usr/share/appdata/io.github.diegopvlk.Dosage.appdata.xml]
    prime:
      - -snap/dosage-tracker

slots:
  dosage-tracker:
    interface: dbus
    bus: session
    name: io.github.diegopvlk.Dosage

apps:
  dosage-tracker:
    command: usr/bin/io.github.diegopvlk.Dosage
    desktop: usr/share/applications/io.github.diegopvlk.Dosage.desktop
    autostart: dosage-tracker-startup.desktop
    common-id: io.github.diegopvlk.Dosage
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gjs/girepository-1.0:${GI_TYPELIB_PATH}
    extensions:
      - gnome
    plugs:
      - audio-playback
      - login-session-observe
```

It's building but I'm getting this after installing and running dosage-tracker:

```
g_module_open() failed for /snap/dosage-tracker/x2/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libxml2.so.2: cannot open shared object file: No such file or directory
/snap/dosage-tracker/x2/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
ERROR: /snap/dosage-tracker/x2/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 127
/snap/dosage-tracker/current/gnome-platform/usr/bin/gjs: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

I tried to install the libraries from the log but I get even more errors.

Any idea on how to fix?

**Reply by soumyaDghosh** [reply]
Hi, is my version working for you? Because I tested it locally and it worked.

**Comment by diegopvlk** [comment]
@soumyaDghosh Hey, so apparently it's possible now to push new snap versions to the store. Have you noticed any issues since core24? Just so I know before I push to stable.

**Reply by soumyaDghosh** [reply]
Is the `core24` version in the store? May I help you with the manifest? I tested a couple of python, rust and electron apps from yesterday. No issue at all, if you're on the stable channel

**Reply by diegopvlk** [reply]
> Is the core24 version in the store?

It's on the edge channel

> May I help you with the manifest? I tested a couple of python, rust and electron apps from yesterday. No issue at all, if you're on the stable channel

I see, everything seems to be working, it's just that error from before:

```
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/diego/snap/dosage-tracker/common/.cache/gio-modules/libgiolibproxy.so
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/diego/snap/dosage-tracker/common/.cache/gio-modules/libgiolibproxy.so
```

I don't know what else needs to be done to fix this

**Reply by soumyaDghosh** [reply]
Those error probably doesn't affect any snap. It's reported though. I guess will be fixed soon.

**Reply by soumyaDghosh** [reply]
Didn't face any issue. So, I guess good to go

**Reply by diegopvlk** [reply]
Alright then, I'll push it. Thanks for the help

**Comment by diegopvlk** [comment]
Hi @soumyaDghosh

I'm trying to fix the snap but I'm failing to understand why during the **building** phase it uses the latest sdk (Adw 1.6.1 and GTK 4.16.3) and when **running** it uses an older one (Adw 1.5.2 and GTK 4.14.4). Shouldn't it use the newer one as well when installing and running? I'm confused 😅

```
name: dosage-tracker
base: core24
adopt-info: dosage-tracker
grade: stable
confinement: strict

parts:
  dosage-tracker:
    plugin: meson
    source: https://github.com/diegopvlk/Dosage.git
    source-tag: "v1.7.4"
    build-environment:
      - GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gjs/girepository-1.0:$GI_TYPELIB_PATH
    meson-parameters:
      - --prefix=/snap/dosage-tracker/current/usr
    build-snaps:
      - blueprint-compiler
    override-pull: |
      craftctl default
      sed -i -e 's|@GJS@|/snap/dosage-tracker/current/gnome-platform/usr/bin/gjs|g' src/io.github.diegopvlk.Dosage.in
    organize:
      snap/dosage-tracker/current: .
    parse-info: [usr/share/appdata/io.github.diegopvlk.Dosage.appdata.xml]
    prime:
      - -snap/dosage-tracker

slots:
  dosage-tracker:
    interface: dbus
    bus: session
    name: io.github.diegopvlk.Dosage

apps:
  dosage-tracker:
    command: usr/bin/io.github.diegopvlk.Dosage
    desktop: usr/share/applications/io.github.diegopvlk.Dosage.desktop
    autostart: dosage-tracker-startup.desktop
    common-id: io.github.diegopvlk.Dosage
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gjs/girepository-1.0:$GI_TYPELIB_PATH
    extensions:
      - gnome
    plugs:
      - audio-playback
      - login-session-observe
```
